const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const source=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n').replace(/render\(\);\s*fetchLive\(\);\s*$/, '');
const elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',style:{},textContent:''});return elements.get(id);};
const listeners={};
const ctx=vm.createContext({console,document:{querySelector:element,getElementById:element,querySelectorAll:()=>[],createElement:()=>({}),head:{appendChild(){}},addEventListener:(type,fn)=>(listeners[type]??=[]).push(fn)},window:{scrollTo(){}},setTimeout,clearTimeout});
vm.runInContext(source,ctx);
vm.runInContext(fs.readFileSync('dashboard.js','utf8'),ctx);
const output=()=>element('#main').innerHTML;
const change=(attrs,value,checked)=>listeners.change.at(-1)({target:{value,checked,dataset:attrs,hasAttribute:n=>Object.hasOwn(attrs,n.replace('data-','').replace(/-([a-z])/g,(_,c)=>c.toUpperCase()))}});
const click=attrs=>listeners.click.at(-1)({target:{closest:()=>({dataset:attrs,hasAttribute:n=>Object.hasOwn(attrs,n.replace('data-','').replace(/-([a-z])/g,(_,c)=>c.toUpperCase()))})}});
const view=v=>vm.runInContext(`state.view=${JSON.stringify(v)};render()`,ctx);
assert.match(output(),/People overview/);
click({dwSector:'Services'});assert.match(output(),/dw-projects/);
const project=vm.runInContext('ALLOCS.find(a=>a.sector==="Services").project',ctx);
click({dwProject:project});assert.match(output(),/Experience \(as recorded\)/);
assert.doesNotMatch(output(),/Person 1 \(placeholder\)/);
view('reporting');assert.match(output(),/Organisation chart/);assert.doesNotMatch(output(),/dw-cube|dw-projects|dw-org-summary/);assert.match(output(),/dw-org-node/);
click({dwReset:''});assert.match(output(),new RegExp(vm.runInContext('PEOPLE.length',ctx)+' people ·'));
change({dwReportSector:''},'Services');
change({dwReportProject:''},project);
const shown=[...output().matchAll(/data-person="([^"]+)"/g)].map(m=>m[1]);
const expected=JSON.parse(vm.runInContext(`JSON.stringify([...new Set(ALLOCS.filter(a=>a.sector==='Services'&&a.project===${JSON.stringify(project)}).map(a=>a.emp))])`,ctx));
assert.deepEqual([...new Set(shown)].sort(),expected.sort());
change({dwReportSector:''},'Manufacturing');assert.doesNotMatch(output(),/dw-cube|dw-projects/);
change({dwReportSector:''},'Services');change({dwReportProject:''},project);
view('kpi');assert.match(output(),/Team reviews/);
const employee=vm.runInContext(`ALLOCS.find(a=>a.sector==='Services'&&a.project===${JSON.stringify(project)}).emp`,ctx);
vm.runInContext(`KPI_RESULTS.push({emp:${JSON.stringify(employee)},sector:'Services',project:${JSON.stringify(project)},role:'Engineer 2',month:'2026-09',score:4,actual:[1,1,1,1,1]},{emp:${JSON.stringify(employee)},sector:'Services',project:'OTHER PROJECT',role:'Engineer 2',month:'2026-09',score:1});render()`,ctx);
assert.doesNotMatch(output(),/OTHER PROJECT/);
click({dwEmployee:employee});assert.match(output(),/Recorded score: <strong>4<\/strong>/);
vm.runInContext(`KPI_RESULTS.push({emp:${JSON.stringify(employee)},sector:'Services',project:${JSON.stringify(project)},role:'Engineer 2',month:'2026-09',score:2});render()`,ctx);
assert.match(output(),/Multiple reviews/);assert.match(output(),/Recorded score: <strong>Not assessed/);
view('available');assert.match(output(),/deployment availability/);
click({dwReset:''});assert.match(output(),/Choose a sector/);
change({dwGroup:'Services'},'',true);assert.match(output(),/Services/);
// UI must not issue writes or persist reassignment into any sheet.
const redesign=fs.readFileSync('dashboard.js','utf8');
assert.doesNotMatch(redesign,/fetch\(|XMLHttpRequest|localStorage|\.send\(/);
assert.match(html,/<script src="dashboard\.js\?v=20260917-wide-responsive-grid"><\/script>/);
assert.match(fs.readFileSync('.github/workflows/deploy-pages.yml','utf8'),/cp dashboard.js site\/dashboard.js/);
console.log('PASS: navigation, project lists, reporting, scoped KPI results, duplicate review handling, read-only UI and packaging');
